#!/usr/bin/env bash
TAG="0.80.1"
SKIA_FEATURES="gl,svg,textlayout,binary-cache"

git clone https://github.com/rust-skia/rust-skia.git
pushd rust-skia;
git checkout $TAG
HASH="$(git rev-parse --short=20 HEAD)"
TARGET="wasm32-unknown-emscripten"
OUTPUT_FILE=skia-binaries-$HASH-$TARGET-"$(echo "$SKIA_FEATURES" | tr ',' '-')".tar.gz
BUILD_PATH=$(cargo build -p skia-safe --release --features "$SKIA_FEATURES" --target $TARGET -q --message-format=json | jq -r 'select((.reason == "build-script-executed") and (.package_id | contains("skia-bindings")) ) | .linked_paths | first')
popd

echo "BUILD_PATH: " $BUILD_PATH

mkdir skia-binaries
cp $BUILD_PATH/*.a skia-binaries/
cp $BUILD_PATH/bindings.rs skia-binaries/
echo $HASH > skia-binaries/key.txt
echo $TAG > skia-binaries/tag.txt
cat > skia-binaries/LICENSE_SKIA  << EOL
Copyright (c) 2011 Google Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

  * Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in
    the documentation and/or other materials provided with the
    distribution.

  * Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
EOL

tar zcvf $OUTPUT_FILE skia-binaries
rm -rf skia-binaries
echo "Generated: $OUTPUT_FILE"